name: tableau_langchain
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.12.2
    - conda-forge::notebook
    - conda-forge::nb_conda_kernels
    - ipykernel
    - python-dotenv
    - pyjwt
    - fastapi
    - tabulate
    - pip=23.3.1
    - pip:
        - langchain
        - langgraph
        - langsmith
        - langchain_anthropic
        - langchain_openai
        - "langserve[all]"
        - langchain_community
        - tavily-python
