[metadata]
name = "tableau_langchain"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[options]
packages = ["find:"]  # Adjust as necessary to include your packages
python_requires = ">=3.12.2"

[options.dependencies]
notebook = "*"
nb_conda_kernels = "*"
ipykernel = "*"
python-dotenv = "*"
pyjwt = "*"
fastapi = "*"
tabulate = "*"

[options.extras]
pip = [
    "langchain",
    "langgraph",
    "langsmith",
    "langgraph-cli",
    "langchain_anthropic",
    "langchain_openai",
    "langchain-pinecone",
    "langserve[all]",
    "langchain_community",
    "llama-index",
    "llama-index-vector-stores-pinecone",
    "pinecone-client[grpc]",
    "semantic-router",
    "tavily-python"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.conda]
channels = ["conda-forge", "defaults"]
