[metadata]
name = "tableau_langchain"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[options]
packages = ["find:"]  # Adjust as necessary to include your packages
python_requires = ">=3.12.2"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.conda]
channels = ["conda-forge", "defaults"]
